### ISSUE TITLE
Containers fail to create and probe exec errors related to seccomp on recent kernel-5.10 versions

### ISSUE THREAD

**Issue by essh** [awslabs/amazon-eks-ami#1219]
**What happened**:

After upgrading EKS nodes from `v20230203` to `v20230217` on our `1.24` EKS clusters after a few days a number of the nodes have containers stuck in `ContainerCreating` state or liveness/readiness probes reporting the following error: 

```
Readiness probe errored: rpc error: code = Unknown desc = failed to exec in container: failed to start exec "4a11039f730203ffc003b7e64d5e682113437c8c07b8301771e53c710a6ca6ee": OCI runtime exec failed: exec failed: unable to start container process: unable to init seccomp: error loading seccomp filter into kernel: error loading seccomp filter: errno 524: unknown
```

This issue is very similar to https://github.com/awslabs/amazon-eks-ami/issues/1179. However, we had not been seeing this issue on previous AMIs and it only started to occur on `v20230217` (following the upgrade from kernel 5.4 to 5.10) with no other changes to the underlying cluster or workloads.

We tried the suggestions from that issue (`sysctl net.core.bpf_jit_limit=452534528`) which helped to immediately allow containers to be created and probes to execute but after approximately a day the issue returned and the value returned by `cat /proc/vmallocinfo | grep bpf_jit | awk '{s+=$2} END {print s}'` was steadily increasing.

**What you expected to happen**:

- Containers to launch successfully and become `Ready`
- Liveness an readiness probes to execute successfully

**How to reproduce it (as minimally and precisely as possible)**:

I don't currently have a reproduction that I can share due to my current one using some internal code (I can hopefully produce a more generic one if required when I get a chance).

As a starting point we only noticed this happening on nodes that had pods scheduled on them which had an `exec` liveness & readiness probe running every 10 seconds that performs a health check against a gRPC service using `grpcurl`. In addition to this we also have a default Pod Security Policy (yes we know they are deprecated 😄) that has the following annotation `seccomp.security.alpha.kubernetes.io/defaultProfileName: docker/default`.

These two conditions seem to be enough to trigger this issue and the values reported by `cat /proc/vmallocinfo | grep bpf_jit | awk '{s+=$2} END {print s}'` will steadily increase over time until containers can no longer be created on the node.

**Anything else we need to know?**:

**Environment**:
- AWS Region: Multiple
- Instance Type(s): Mix of x86_64 and arm64 instances of varying sizes
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): `"eks.4"`
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): `"1.24"`
- AMI Version: `v20230217`
- Kernel (e.g. `uname -a`): `5.10.165-143.735.amzn2.x86_64 #1 SMP Wed Jan 25 03:13:54 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
- Release information (run `cat /etc/eks/release` on a node):

```
BASE_AMI_ID="ami-09bffa74b1e396075"
BUILD_TIME="Fri Feb 17 21:59:10 UTC 2023"
BUILD_KERNEL="5.10.165-143.735.amzn2.x86_64"
ARCH="x86_64"
```

### Official Guidance

Kubernetes pods using SECCOMP filtering on EKS optimized AMIs based on Linux Kernel version 5.10.x may get stuck in `ContainerCreating` state or their liveness/readiness probes fail with the following error:

    unable to init seccomp: error loading seccomp filter into kernel: error loading seccomp filter: errno 524

When a process with SECCOMP filters creates a child process, the same filters are inherited and applied to the new process. The Amazon Linux kernel versions 5.10.x are affected by a memory leak that occurs when parent process is terminated while creating a child process. When the total amount of memory allocated for SECCOMP filter is over the limit, a process cannot create a new SECCOMP filter.  As a result, the parent process fails to create a new child process and the above error message will be logged.

This issue is more likely to be encountered with kernel versions `kernel-5.10.176-157.645.amzn2` and `kernel-5.10.177-158.645.amzn2` where the rate of the memory leak is higher. 

Amazon Linux will be releasing the fixed kernel by May 1st, 2023. We will be releasing a new set of EKS AMIs with the updated kernel latest by May 3rd, 2023.

**Comment by essh** [comment]
I've managed to build a reliable reproduction for this issue that I can now share. A quick summary is that the impact seems to depend on instance type. I have been able to consistently reproduce this issue on `c5d.xlarge` & `c5a.xlarge` instance types (`x86_64`). I have seen some `bpf_jit` memory growth on `c6g.xlarge` instances (`arm64`) but it seems a bit slower and I haven't seen containers fail to create on these nodes yet as a result. I can't reproduce this issue on a `t3a.large` instance as `bpf_jit` memory levels remain pretty consistent.

The easiest way to reproduce this is to spin up a fresh EKS 1.24 cluster and add a single node of the required instance type (this makes it easier to observe) running EKS AMI `v20230217` (or `v20230304`). Then run the following commands:

```
kubectl delete clusterrolebinding eks:podsecuritypolicy:authenticated
kubectl delete clusterrole eks:podsecuritypolicy:privileged
kubectl podsecuritypolicy eks.privileged
kubectl apply -f https://gist.githubusercontent.com/essh/f7dd219a48df25e7294847484da112b7/raw/503ff9a8f32f19430040cd65c213479979bfcc3c/bpf-jit-leak.yaml
```

This removes the `eks.privileged` PSP, installs PSPs that use seccomp and starts up a simple app with some `exec` probes that trigger the issue. The container used for this app is built from the source available at https://github.com/essh/grpc-greeter-node.

Once this is running you can observe memory growth by executing `sudo cat /proc/vmallocinfo | grep bpf_jit | awk '{s+=$2} END {print s}'` on the node. You can tweak the replica count up and down to speed up/slow down this process. If you leave it long enough the value will exceed `net.core.bpf_jit_limit` and you will end up with failure to create containers/exec probs. We were seeing this after about 2-3 days with our node types/workloads in our environment.

This same test against EKS AMI `v20230203` nodes or lower (kernel 5.4) does not exhibit this issue.

**Comment by cartermckinnon** [comment]
@essh really appreciate the details; I'm following up internally with our kernel folks and will update here as I try to reproduce.

**Comment by borkmann** [comment]
> @essh really appreciate the details; I'm following up internally with our kernel folks and will update here as I try to reproduce.

@essh @cartermckinnon I happened to take a look at this recently, and tried to reproduce this on latest bpf tree kernel. I dumped the values around bpf_jit_charge_modmem and bpf_jit_uncharge_modmem, in particular the size passed in and the value of bpf_jit_current after the operation. They all look sane to me. For example, when running tcpdump with a specific filter (e.g. `tcpdump -i lo tcp`) but also a test application loading a seccomp BPF policy, and I can see the bpf_jit_current counter going up and then discharging again with the same value. Also I tested on native eBPF programs, same here. This all looks good to me.

@cartermckinnon if you follow-up with kernel folks, I'd suggest to check the same.. meaning, is bpf_jit_current steadily increasing (and never decreasing) or does it look sane when loading/unloading programs and just the default limit is too low.

Either way, the default limit for any BPF user for the JIT is currently set to 1/4 of the module memory space, and I'll send an upstream patch (and also recommend for stable) to bump this default limit to 1/2.

From @essh's description though, it looks like the counter is never decreasing which looks like a kernel bug if indeed true, perhaps some backport going wrong, etc. Would be good to double check.

**Comment by borkmann** [comment]
Looks like potentially missing kernel commit in seccomp causing this issue: a1140cb215fa ("seccomp: Move copy_seccomp() to no failure path.") (via https://lore.kernel.org/bpf/20230321170925.74358-1-kuniyu@amazon.com/)

**Comment by stevo-f3** [comment]
Is memleak (mentioned in https://lore.kernel.org/bpf/20230321170925.74358-1-kuniyu@amazon.com/) fixed in 5.4? If so, would it make sense for kernel in amazon-eks-ami published AMI to be downgraded from 5.10 to 5.4 until memleak fix is "backported" to 5.10 and newer?

**Comment by borkmann** [comment]
5.4 kernel would not be affected as it does not seem to have the offending commit 3a15fb6ed92c ("seccomp: release filter after task is fully dead") which a1140cb215fa ("seccomp: Move copy_seccomp() to no failure path.") fixes.

**Comment by stevo-f3** [comment]
Thanks @borkmann for heads up!

It's non trivial to downgrade the kernel downstream when building AMI based on this upstream EKS node AMI which is on kernel 5.10; It would be great that  this upstream AMI gets downgraded to kernel 5.4 (at least until memory leak is backported to affected 5.10+ kernels), and anyone that really needs 5.10 or newer and can live with known memory leak, can more easily upgrade the kernel on their own in custom AMI based on the upstream one. WDYT?

**Comment by borkmann** [comment]
I'll defer to AWS folks with regards to your question, Cc @cartermckinnon. Hopefully this can be fixed quickly by cherry-picking the two commits below for EKS kernel.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a1140cb215fa13dcec06d12ba0c3ee105633b7c4
https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf.git/commit/?id=10ec8ca8ec1a2f04c4ed90897225231c58c124a7

**Comment by dims** [comment]
@borkmann ACK on behalf of @cartermckinnon. please give us some time to do things...

**Comment by cartermckinnon** [comment]
Unfortunately the series of patches we've cherrypicked internally does not seem to resolve the issue. We're still looking into it.

I was *not* able to reproduce this with 5.15, so we're diff-ing the changelog as well.

**Comment by cartermckinnon** [comment]
> It's non trivial to downgrade the kernel downstream when building AMI based on this upstream EKS node AMI which is on kernel 5.10

@stevo-f3 This should do it:
```
yum versionlock delete kernel
amazon-linux-extras disable kernel-5.10
amazon-linux-extras enable kernel-5.4
yum install -y kernel
```

At present, we have more users needing 5.10 who are *not* experiencing this leak than those who are; downgrading the official build to 5.4 would be a last resort if we can't put a fix together.

**Comment by stevo-f3** [comment]
We can't use 5.15 - recently downgraded to 5.10, with 5.15 were experiencing kernel panics on instance startup, on production only.

Thanks for downgrade to 5.4 instructions, is trivial after all, will use it at least until fix available.

**Comment by q2ven** [comment]
After backporting a1140cb215fa ("seccomp: Move copy_seccomp() to no failure path.") to our 5.10 kernel, I didn't see any memleak with @essh 's repro.  I will release a new kernel with the commit and post the backport patch to the upstream 5.10 tree as well.

**Comment by cartermckinnon** [comment]
Thank you @q2ven!

**Comment by rarecrumb** [comment]
I'm running Karpenter and running into this issue. Is there any fix I can apply? Very worrying.

**Comment by dims** [comment]
@rarecrumb looking at the kernel version of the newest release:
https://github.com/awslabs/amazon-eks-ami/releases/tag/v20230411#:~:text=amazon%2Deks/1.22.17//-,AMI%20details,-%3A

it says:
`Kubernetes 1.24 and above: 5.10.176-157.645.amzn2`

Which is older than the AMI i pointed to above:
`kernel-5.10.177-158.645.amzn2`

So please wait for next drop or build an AMI with the kernel version above.

cc @mmerkes @cartermckinnon

**Comment by rarecrumb** [comment]
> @rarecrumb looking at the kernel version of the newest release: https://github.com/awslabs/amazon-eks-ami/releases/tag/v20230411#:~:text=amazon%2Deks/1.22.17//-,AMI%20details,-%3A
> 
> it says: `Kubernetes 1.24 and above: 5.10.176-157.645.amzn2`
> 
> Which is older than the AMI i pointed to above: `kernel-5.10.177-158.645.amzn2`
> 
> So please wait for next drop or build an AMI with the kernel version above.
> 
> cc @mmerkes @cartermckinnon

How long until a new AMI is published with this fix in place?

**Comment by essh** [comment]
> @essh Can you please this kernel? `kernel-5.10.177-158.645.amzn2` and let us know?

I've tried updating to `kernel-5.10.177-158.645.amzn2` as suggested but my reproduction is still showing continuing growth when testing with the `sudo cat /proc/vmallocinfo | grep bpf_jit | awk '{s+=$2} END {print s}'` command. If it's felt this kernel should fix the issue is there anything else I could do to confirm this outside of waiting some number of days for things to start failing?

**Comment by SimonKO9** [comment]
I can also confirm that issues still persist with `5.10.176-157.645.amzn2`.

**Comment by Wyifei** [comment]
After Upgrade EKS to 1.25, we also met this issue.
We're using EKS managed group, will the Kernel fix apply to the EC2 node automatically?

**Comment by billo-zymantas** [comment]
Having same issue with EKS 1.26 managed group.

**Comment by kirinnee** [comment]
Having the same issue with EKS 1.25. AMI version: `5.10.176-157.645.amzn2.x86_64`

**Comment by tomislater** [comment]
The same problem for this setup:
```
Kernel version: 5.10.176-157.645.amzn2.x86_64
Kubelet version: v1.24.11-eks-a59e1f0
```

On:
```
Kernel version: 5.4.226-129.415.amzn2.x86_64
Kubelet version: v1.24.7-eks-fb459a0
```
works great.

**Comment by dims** [comment]
> is still showing continuing growth

@essh growth at the same pace as before or is it slower growth rate originally?

**Comment by dims** [comment]
@SimonKO9 what's your scenario? (seccomp? cilium?)

**Comment by SimonKO9** [comment]
@dims it's seccomp, containers running on a code crash eventually and no more can be started (unless seccomp=unconfined is passed explicitly). We downgraded to 5.4 and we're running without issues now.

**Comment by rarecrumb** [comment]
I've switched to Bottlerocket

**Comment by alexku7** [comment]
Have the same issue after upgrading to the latest v20230411.

The nodes get the error within less than 1 day!

Reverted to previous v20230406 seems solved the problem

**Comment by essh** [comment]
> @essh growth at the same pace as before or is it slower growth rate originally?

The pace felt roughly the same but I did not perform a side by side comparison at this stage.

**Comment by ChrisV78** [comment]
We have the same issue, hoping for a quick fix, otherwise have to go to BottleRocket I guess.

**Comment by cartermckinnon** [comment]
We're following up on this with our kernel folks; we believe we've identified the necessary patches. I'll update here once we've verified and have a kernel build in the pipeline.

**Comment by dougbaber** [comment]
Just wanted to make sure you are aware that we see the issue with ECS as well, not just EKS.  We have replicated it with kernel `5.10.177-158.645.amzn2`

**Comment by mynkkmr** [comment]
We created a new EKS cluster on version 1.24, After that below error started to show while container are starting up.

`Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: unable to init seccomp: error loading seccomp filter into kernel: error loading seccomp filter: errno 524: unknown`

**Comment by reedjosh** [comment]
> We created a new EKS cluster on version 1.24, After that below error started to show while containers are starting up.
> 
> `Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: unable to init seccomp: error loading seccomp filter into kernel: error loading seccomp filter: errno 524: unknown`
> 
> Any plans of reverting this to the last stable version till the time AWS finds a fix?


This ☝️ 

Why is a broken AMI still the default for Amazon's managed node groups?

Can't that be backed out or the release pulled?

**Comment by islishude** [comment]
Can team rollback the commits and make a new release?

**Comment by radimk** [comment]
FWIW with `eksctl` it is possible to pin previous version with
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: k8s
managedNodeGroups:
  - name: nodegroup
    releaseVersion: 1.24.11-20230406  # or any other from https://github.com/awslabs/amazon-eks-ami/releases
    ...
```
Of course this is very unfortunate bug that renders our nodes unusable within day or two even with increased `bpf_jit_limit` and we're hoping for a quick fix.

**Comment by mmerkes** [comment]
Official guidance:

Kubernetes pods using SECCOMP filtering on EKS optimized AMIs based on Linux Kernel version 5.10.x may get stuck in `ContainerCreating` state or their liveness/readiness probes fail with the following error:

    unable to init seccomp: error loading seccomp filter into kernel: error loading seccomp filter: errno 524

When a process with SECCOMP filters creates a child process, the same filters are inherited and applied to the new process. The Amazon Linux kernel versions 5.10.x are affected by a memory leak that occurs when parent process is terminated while creating a child process. When the total amount of memory allocated for SECCOMP filter is over the limit, a process cannot create a new SECCOMP filter.  As a result, the parent process fails to create a new child process and the above error message will be logged.

This issue is more likely to be encountered with kernel versions `kernel-5.10.176-157.645.amzn2` and `kernel-5.10.177-158.645.amzn2` where the rate of the memory leak is higher. 

Amazon Linux will be releasing the fixed kernel by May 1st, 2023. We will be releasing a new set of EKS AMIs with the updated kernel latest by May 3rd, 2023.

**Comment by KrisJohnstone** [comment]
Same issue is impacting us, subbed for updates.

**Comment by mchlbataller** [comment]
Subbing for updates as well, this issue has been impacting us for days now.

**Comment by marcincuber** [comment]
Same issue happening on my clusters. Subbing for latest updates.

**Comment by bla-ckbox** [comment]
Hi, the same for me, with EKS 1.26 AMI version: 5.10.176-157.645.amzn2.x86_64

**Comment by macmiranda** [comment]
Hey guys, appreciate you're all subbing but think of the people that are already subbed getting all these pointless messages.

If you're not gonna add any information that's relevant to the resolution of the issue please refrain from sending another message and just click the subscribe button.

**Comment by nille** [comment]
The kernel fix seems to have been released now, as 5.10.178-162.673.amzn2.x86_64.

**Comment by mmerkes** [comment]
Yes, it's available. Folks that manage custom AMIs can start using the kernel and we're preparing AMIs for release on Wednesday that will include the latest kernel.

**Comment by mmerkes** [comment]
The `v20230501` release has started now, and it includes `5.10.178-162.673.amzn2.x86_64` for all AMIs that use 5.10 kernels. We have tested the kernel and expect it to resolve this issue for customers. New AMIs should be available in all regions late tonight (PDT).

**Comment by mmerkes** [comment]
`v20230501` is available in all regions now! Update to the latest EKS Optimized AMIs and this issue should be resolved.

**Comment by michelesr** [comment]
Is the kernel fix actually fixing the bug for good or is it just bumping the default bpf jit memory limit?

**Comment by dims** [comment]
@michelesr https://lore.kernel.org/bpf/20230321170925.74358-1-kuniyu@amazon.com/

**Comment by dims** [comment]
thanks @ljosyula @mmerkes @cartermckinnon @q2ven 

https://github.com/awslabs/amazon-eks-ami/releases/tag/v20230501

**Comment by skupjoe** [comment]
We are still seeing this issue across our prod cluster after upgrading to 1.24.

Increasing the `bpf_jit_limit` does indeed fix the issue for pods stuck in `Pending` due to this seccomp issue. But it is, at best, only a temporary fix, and after a few days the new limit again gets saturated due to the underlying memory leak and we are faced with this problem again.

Looks like we are going to have to downgrade to kernel 5.4 as the only option for now.

**Comment by skupjoe** [comment]
That said, can we re-open this issue?

I see from the commits referenced to this issue that AWS team is still trying to wrangle/fix this bug, and so obviously this is still actively being worked on. But this issue being in `Closed` state falsely gives the impression that it has been fixed.

(Also, I am surprised that not more people are reporting this? Do we just have an unnatural amount of liveness/health check probes or something?)

**Comment by cartermckinnon** [comment]
@skupjoe We haven't had any reports of this since https://github.com/awslabs/amazon-eks-ami/issues/1219#issuecomment-1534536682, can you confirm the kernel version you're on?

**Comment by skupjoe** [comment]
I downgraded from 5.10 to `5.4.283-195.378.amzn2.x86_64` and unfortunately it is still happening after about 3.5 days of uptime.

Increasing the `bpf_jit_limit` helps things for another ~3 days, but then the issue comes back.

It seems to happen on instances of any size/type- I am looking at it happening on a `c6a.large`, `m5a.8xlarge`, and a `m5a.2xlarge` nodes.

I am desperate to get this fixed and it has been happening to me since eks 1.24 upgrade. And now I am on 1.27 and will be upgrading to 1.28 tonight.

We are not using PSP and I don't see any seccomp config set anywhere at the pod level or on my k8s node config:
```
[root@ip-10-0-82-217 /]# sudo cat /etc/containerd/config.toml | grep -i seccomp
```

But the kernel supports it:
```
[root@ip-10-0-104-41 /]# grep SECCOMP /boot/config-$(uname -r)
CONFIG_HAVE_ARCH_SECCOMP=y
CONFIG_HAVE_ARCH_SECCOMP_FILTER=y
CONFIG_SECCOMP=y
CONFIG_SECCOMP_FILTER=y
```

Can we re-open this? Or should I raise a new issue?

**Comment by skupjoe** [comment]
I am considering moving away from amazon-eks-ami as I am desperate to get this issue fixed. Can anybody suggest a good replacement? Maybe [Bottlerocket](https://github.com/awsdocs/amazon-eks-user-guide/blob/main/doc_source/eks-optimized-ami-bottlerocket.md)?

**Comment by cartermckinnon** [comment]
@skupjoe If you're seeing this issue on the 5.4 kernel branch, it is definitely not the same issue described above. Please open a new issue or an AWS support case and we can take a look.

> I see from the commits referenced to this issue that AWS team is still trying to wrangle/fix this bug, and so obviously this is still actively being worked on. But this issue being in Closed state falsely gives the impression that it has been fixed.

The commit references are a kernel change that was made by a community member to increase the default JIT space for BPF programs. It is not a fix for the issue described here, which was a memory leak. The memory leak was fixed by @q2ven (IIRC). We have no reason to think there's been a regression.
