### ISSUE TITLE
Sandbox container image being GC'd in 1.29

### ISSUE THREAD

**Issue by nightmareze1** [awslabs/amazon-eks-ami#1597]
AMI: amazon-eks-node-1.29-v20240117

```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/pause:3.5": failed to pull image "602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/pause:3.5": failed to pull and unpack image "602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/pause:3.5": failed to resolve reference "602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/pause:3.5": unexpected status from HEAD request to https://602401143452.dkr.ecr.eu-west-2.amazonaws.com/v2/eks/pause/manifests/3.5: 401 Unauthorized
```

1 day after upgrading EKS to 1.29

**Comment by cartermckinnon** [comment]
It sounds like something deleted your pause container image. You can look for `DeleteImage` CRI calls in your `containerd` logs, and make sure that the `--pod-infra-container-image` flag passed to `kubelet` matches the `sandbox_image` in `/etc/containerd/config.toml`.

**Comment by nightmareze1** [comment]
[~]#  systemctl kubelet status
```
          └─3729 /usr/bin/kubelet --config /etc/kubernetes/kubelet/kubelet-config.json --kubeconfig /var/lib/kubelet/kubeconfig --container-runtime-endpoint unix:///run/containerd/containerd.sock --image-credential-provider-config /etc/eks/image-credential-provider/config.json --image-credential-provider-bin-dir /etc/eks/image-credential-provider --pod-infra-container-image=602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/pause:3.5 --v=2 
```

[~]# cat /etc/containerd/config.toml |grep 602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/pause:3.5

```
sandbox_image = "602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/pause:3.5"
```

**Comment by jrsparks86** [comment]
We also have noticed this issue after updating to 1.29. If we rotate out the nodes it recovers for some time then comes back a day later.

**Comment by nightmareze1** [comment]
I'm using a temporal workaround proposed by a person in the issue created in aws-node repo(I modified a little but works)

```
curl -fsL -o crictl.tar.gz https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.29.0/crictl-v1.29.0-linux-amd64.tar.gz
tar zxf crictl.tar.gz
chmod u+x crictl
mv crictl /usr/bin/crictl


cat <<EOF > /etc/eks/eks_creds_puller.sh
IMAGE_TOKEN=@@@(aws ecr get-login-password --region eu-west-2)
crictl --runtime-endpoint=unix:///run/containerd/containerd.sock  pull --creds "AWS:\$IMAGE_TOKEN" 602401143452.dkr.ecr.eu-west-2.amazonaws.com/eks/pause:3.5
EOF
 
sed -i 's/@@@/\$/g' /etc/eks/eks_creds_puller.sh

chmod u+x /etc/eks/eks_creds_puller.sh

echo "*/5 * * * * /etc/eks/eks_creds_puller.sh >> /var/log/eks_creds_puller 2>&1" | crontab -

```

**Comment by ohrab-hacken** [comment]
I am experience same issue. `--pod-infra-container-image` flag is set on kubelet. I found that my disk on node really become full after some time and kubelet garbage collector delete `pause` image. So, instead of delete different images, it deletes pause image. After pause image deleted, node doesn't work.
I found the reason of full disk. In my case, I have `ttlSecondsAfterFinished: 7200` for dagster jobs, and it consume all disk space. I've changed it to `ttlSecondsAfterFinished: 120` and jobs cleaned up more frequently and we don't have this issue any more.
It's strange cause I didn't have this issue on 1.28, and I didn't change any Dagster configuration between version upgrade. My guess, it kubelet image garbage collector works different in 1.28 and 1.29.

**Comment by dogsbody-ashley** [comment]
We're experiencing the same issue as well.

**Comment by wiseelf** [comment]
I'm  having that same issue after upgrading to 1.29 on both AL2 and Bottlerocket nodes.

**Comment by havilchis** [comment]
The Kubelet flag `--pod-infra-container-image` is deprecated in 1.27+ [https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/]. The current implementation is that GC reads the properties of the Image set by the Container Runtime.

In the case of containerd, the GC should avoid images tagged with the property "pinned: true".

And containerd should flag the sandbox_image as pinned [https://github.com/containerd/containerd/pull/7944].

I believe that issue is related to containerD and the sandbox_image. 

Although is set in config.toml, this is not flagged as "pinned: true". 

I do not know if this is a general issue in ContainerD, but at least in my EKS Cluster in 1.29 the sandbox image appears as "pinned:false";

```
./crictl images | grep pause | grep us-east-1 | grep pause
602401143452.dkr.ecr-fips.us-east-1.amazonaws.com/eks/pause                    3.5                          6996f8da07bd4       299kB
602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/pause                         3.5                          6996f8da07bd4       299kB

./crictl inspecti 6996f8da07bd4 | grep pinned
    "pinned": false
```

**Comment by cartermckinnon** [comment]
It definitely seems like image pinning is the problem here. I'm trying to put a fix together 👍

**Comment by cartermckinnon** [comment]
I think the issue here is the version of `containerd` being used by Amazon Linux does not have pinned image support, which was added in `1.7.3`: https://github.com/containerd/containerd/compare/v1.7.2...v1.7.3

I'm verifying that this hasn't been cherry-picked by the AL team. We'll probably have to do a hotfix in the immediate term.

**Comment by cartermckinnon** [comment]
AL intends to push `containerd-1.7.11` to the package repositories soon, but I'll go ahead and put together a hotfix on our end.

**Comment by cartermckinnon** [comment]
I think the best bandaid for now is to periodically pull the sandbox image, that's what #1601 does. @mmerkes @suket22 PTAL.

**Comment by Idan-Lazar** [comment]
any updates?

**Comment by StefanoMantero** [comment]
We're experiencing the same issue as well, pretty random tho, any updates ?

**Comment by dekelummanu** [comment]
+1

**Comment by Tenzer** [comment]
A small workaround I've done on our end to help alleviate the issue, is to give the nodes in the cluster a bigger disk. This means it will take longer time for the nodes to use enough disk space to trigger the garbage collection which deletes the pause image.

**Comment by wiseelf** [comment]
> A small workaround I've done on our end to help alleviate the issue, is to give the nodes in the cluster a bigger disk. This means it will take longer time for the nodes to use enough disk space to trigger the garbage collection which deletes the pause image.

I did the same, it just increases a time for issue to occur and brings additional expenses. Agree that it is a top priority issue because it is impossible to downgrade to 1.28 without recreating the cluster.

**Comment by cartermckinnon** [comment]
`containerd` 1.7.3+ should have the image pinning functionality; but in my tests I only see the CRI response report `pinned: true` when I manually label the image with `io.cri-containerd.pinned=pinned`. It doesn't seem to be labeling the configured `sandbox_image` automatically. I think we'll have to use a hotfix for now.

**Comment by dims** [comment]
cc @henry118

**Comment by mlagoma** [comment]
> While we work to get a fix out, swapping out the sandbox container image to one that doesn't require ECR credentials is another workaround:
> 
> * `registry.k8s.io/pause:3.9`
> * `public.ecr.aws/eks-distro/kubernetes/pause:v1.29.0-eks-1-29-latest`

Greetings, does anybody have any guidance on how I can make this modification to my EKS cluster? Is it part of the Dockerfile build of the container image? The kube deployment manifest (which uses my container image)?  Somewhere else? Better to just wait it out for the fix?

**Comment by dims** [comment]
@mlagoma `/etc/containerd/config.toml` is the configuration file for containerd, you will see an entry (key / value) for a `sandbox_image` this points to an image in ECR usually. @cartermckinnon was talking about switching that.

However, it is better to talk to AWS support and get help if you are not comfortable.

**Comment by sebastianplawner** [comment]
Reading from a comment at https://github.com/awslabs/amazon-eks-ami/pull/1601, it is possible to use the 1.28 AMI version. So pods can be created while this issue is resolved in version 1.29

In my case I use Karpenter and I added the following code to the EC2NodeClass, within the spec block:
```
amiSelectorTerms:
  - name: amazon-eks-node-1.28-*
```

I got the image name from [here](https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#Images:)
And the documentation on how to modify NodeClass is [here](https://karpenter.sh/docs/concepts/nodeclasses/#specamiselectorterms)

This way, all nodes started rotating to the latest available version of 1.28

**Comment by victor-chan-groundswell** [comment]
I verified that rolling the node AMI (I use AL2) back to a 1.28 version is a good workaround as well.  I have everything tied to a ASG/Launch Template so it's just a matter of going back to a previous version of a launch template.

**Comment by dims** [comment]
@victor-chan-groundswell thanks for confirming!

**Comment by mlagoma** [comment]
Updated Managed EKS node in Clusters -> Computer -> Node group and working fine per merge of #1601

**Comment by macnibblet** [comment]
@mlagoma Which EKS AMI Version are you on because we updated this morning and we are still facing the same issue

**Comment by dogsbody-ashley** [comment]
Thank you @macnibblet for the changelog link, 
I upgraded this morning and wondered why we were still seeing the Sandbox error.
(Using EKS 1.29 still)

**Comment by cartermckinnon** [comment]
This was closed by a PR hook; we'll re-close it once an AMI release is available with a fix. 👍

**Comment by tzneal** [comment]
As an immediate workaround to prevent this from occurring until the new AMI is released, you can:

1. Determine the sandbox image that is configured for use in the cluster by looking at the /etc/containerd/config.toml on a node in the cluster:
```
$ grep sandbox /etc/containerd/config.toml
sandbox_image = "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/pause:3.5"
```

2. Modify and deploy the following DaemonSet to reference the sandbox image that containerd uses:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prevent-sandbox-gc
  namespace: kube-system
  labels:
    app: prevent-sandbox-gc
spec:
  selector:
    matchLabels:
      name: prevent-sandbox-gc
  template:
    metadata:
      labels:
        name: prevent-sandbox-gc
    spec:
      tolerations:
      # run everywhere regardless of taints
      - operator: Exists
      containers:
      - name: pause
        image: <sandbox image source>
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
```



Note: This will not fix nodes that are already broken, but it will mark the sandbox image as in use from kubelet's perspective and prevent the image from being garbage collected.

**Comment by muneebcui** [comment]
any luck with the issue?

**Comment by dims** [comment]
> any luck with the issue?

Hang in there please! :)

**Comment by foluso-adewumi** [comment]
@tzneal please how do I remove your workaround when a new AMI is released that fixes the issues ?

**Comment by tzneal** [comment]
> @tzneal please how do I remove your workaround when a new AMI is released that fixes the issues ?

You can just delete that dameonset with `kubectl delete daemonset -n kube-system prevent-sandbox-gc`.

**Comment by cartermckinnon** [comment]
This issue should be fixed in AMI release [v20240202](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20240202). We were able to include `containerd-1.7.11` which properly reports the `sandbox_image` and pinned to `kubelet` after the changes in #1605.

**Comment by dims** [comment]
Follow up to https://github.com/awslabs/amazon-eks-ami/pull/1601#issuecomment-1919628687

> @dims your comment is not helpful, the issue we're having is in production and is directly related to this PR. So how about you guys get cracking on this and get it merged instead of telling me to report things to my TAM!

@spatelwearpact Please see note above from @cartermckinnon

**Comment by arvindpunk** [comment]
Can confirm [v20240202](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20240202) fixed the issue. Unfortunately since GC occurs at random times - we definitely incurred a downtime before we noticed the issue. Perhaps sending out a notification to everyone who's on this AMI version before their GC occurs is a good idea.

**Comment by dims** [comment]
@arvindpunk yep! +1 to the suggestion. in the works.. waiting to make sure it sticks.

**Comment by marcin99** [comment]
@doramar97  downgrade workers with image v1.28 and it's better to wait a few weeks with the update, because they don't test anything (i.e. they test it in production with customers)

**Comment by doramar97** [comment]
@marcin99 I'm not sure that I can downgrade EKS version without replacing the cluster with a new one, It is a production cluster and i'm looking for a reliable fix until they will issue a fix.

**Comment by dims** [comment]
> @doramar97 downgrade workers with image v1.28 and it's better to wait a few weeks with the update, because they don't test anything (i.e. they test it in production with customers)

you are welcome to do what works for you. please bear with us as this was a tricky one.

**Comment by dims** [comment]
> any updates on bottlerocket ?

@marcin99 if you need a solid ETA for production, it's better to approach via support escalation channels. suffice to say, it's in progress.

**Comment by tzneal** [comment]
> @marcin99 I'm not sure that I can downgrade EKS version without replacing the cluster with a new one, It is a production cluster and i'm looking for a reliable fix until they will issue a fix.

The BottleRocket team [confirmed](https://github.com/bottlerocket-os/bottlerocket/issues/3745#issuecomment-1924526275) that the DaemonSet prevention solution I posted above works for BotleRocket as well.

**Comment by marcin99** [comment]
@doramar97  you don't need downgrade cluster version, but you can use the image from the previous version for workers

**Comment by RamazanBiyik77** [comment]
> This issue should be fixed in AMI release [v20240202](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20240202). We were able to include `containerd-1.7.11` which properly reports the `sandbox_image` as pinned to `kubelet`, after the changes in #1605.

How can i apply this changes to my existing AMI?

i can confirm that my sandbox image is still 602401143452.dkr.ecr.eu-central-1.amazonaws.com/eks/pause:3.5.

**Comment by RamazanBiyik77** [comment]
Okay found it on AWS EKS Compute section. There was a notification for new AMI release.

**Comment by bryantbiggs** [comment]
@odellcraig you do that via the `release_version`

**Comment by odellcraig** [comment]
@bryantbiggs Thank you.

For anyone using Terraform and eks_managed_node_groups you can specify using:
```
eks_managed_node_groups = {
    initial = {
      ami_release_version = "1.29.0-20240227" # this is the latest version as of this comment
      name           = "..."
      instance_types = [...]
      min_size       = ...
      max_size       = ...
      desired_size   = ...
...
```

**Comment by korncola** [comment]
can you please fix the damn issue after half a year? Still happens with EKS managed nodegroup and AMI 
`amazon/amazon-eks-node-1.29-v20240522`

Error in kubelet on node:
`unexpected status from HEAD request to https://602401143452.dkr.ecr.eu-central-1.amazonaws.com/v2/eks/pause/manifests/3.5: 403 Forbidden"`

migration to EKS halted here

**Comment by tzneal** [comment]
Are the permissions on your node role correct per https://docs.aws.amazon.com/eks/latest/userguide/create-node-role.html? Specifically, does it have the [AmazonEC2ContainerRegistryReadOnly](https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AmazonEC2ContainerRegistryReadOnly.html) policy?

**Comment by shamallah** [comment]
> [AmazonEC2ContainerRegistryReadOnly](https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AmazonEC2ContainerRegistryReadOnly.html) policy?

The policy is attached.

**Comment by korncola** [comment]
Policy [AmazonEC2ContainerRegistryReadOnly](https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AmazonEC2ContainerRegistryReadOnly.html) is attached here also.
Cant you just use a REAL public repo instead of this half baked half private/public repo in the configs and init scripts? cause hacking the bootstrapping script with `public.ecr.aws/eks-distro/kubernetes/pause:v1.29.0-eks-1-29-latest` works - but only until reboot, cause init-scripts will always place this damn non working URL in `/etc/containerd/config.toml`

**Comment by cartermckinnon** [comment]
@korncola can you open a ticket with AWS support so we can look into the specifics of your environment?

**Comment by korncola** [comment]
thanks @cartermckinnon , will do that.
But still: Why no **true** public repo?!

Did a cluster via terraform and GUI, triple checked policies. Also disabled all SCP. Still same error.
Also nodegroups with AL2023 image or AL2 no success.

**Comment by cartermckinnon** [comment]
ECR Public is only hosted in a few regions; so we still use regional ECR repositories for lower latency and better availability. ECR Public also has a monthly bandwidth limit for anonymous pulls that cannot be increased; so if you're using it in production, make sure you're not sending anonymous requests.

**Comment by korncola** [comment]
#and better availability.
yeah i see the availability in this and the other tickets...
#ECR Public also has a monthly bandwidth limit for anonymous pulls that cannot be increased;
As i said above use a **real** public service...
And AWS owns that service, so make it worth...

**Comment by bryantbiggs** [comment]
@korncola lets keep it professional. The best course of action is to work with the team through the support ticket. There are many factors that go into decisions that users are not usually aware of. The team is very responsive in terms of investigating and getting a fix rolled out (as needed)

**Comment by korncola** [comment]
yep you are right 👍  team here is very helpful and responsive, thank you for the support here! Will report when issue is resolved, so others can use that info.

**Comment by mlagoma** [comment]
If I understand correctly, the same or a similar (in that it will definitely occur over time) bug was perhaps reintroduced/introduced? So should it be advised to not upgrade nodes? Or is this a separate issue (e.g. anonymous pulls)?

No sign of the issue on older version (1.29.0-20240202)

**Comment by cartermckinnon** [comment]
No, at this point we don’t have evidence of a new bug or a regression.

I’m going to lock this thread to avoid confusion, please open a new issue for follow-ups.
